"""google auth fields

Revision ID: 150ffd412ba5
Revises: 2ffb057a8a7d
Create Date: 2026-02-02 16:41:09.639256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '150ffd412ba5'
down_revision: Union[str, Sequence[str], None] = '2ffb057a8a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('short_user_id_fkey'), 'short', type_='foreignkey')
    op.drop_constraint(op.f('shorttag_short_id_fkey'), 'shorttag', type_='foreignkey')
    op.drop_constraint(op.f('shorttag_tag_id_fkey'), 'shorttag', type_='foreignkey')
    op.add_column('user', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_provider_user_id'), 'user', ['provider_user_id'], unique=True)
    op.drop_column('user', 'password')
    op.drop_constraint(op.f('usertag_user_id_fkey'), 'usertag', type_='foreignkey')
    op.drop_constraint(op.f('usertag_tag_id_fkey'), 'usertag', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('usertag_tag_id_fkey'), 'usertag', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('usertag_user_id_fkey'), 'usertag', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_provider_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email_verified')
    op.drop_column('user', 'provider_user_id')
    op.drop_column('user', 'name')
    op.create_foreign_key(op.f('shorttag_tag_id_fkey'), 'shorttag', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('shorttag_short_id_fkey'), 'shorttag', 'short', ['short_id'], ['id'])
    op.create_foreign_key(op.f('short_user_id_fkey'), 'short', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
